### PR TITLE
Restify-based client

### LINKED ISSUE #25: Client: Errors and restify.JsonClient
CPU sky-rockets on errors, since there is no timeout between retrying. Pretty awkward, we should back-off or at least have 1 second timeout. Thought we can work around this by simply using `setTimeout`, it is probably worth to switch to `restify.JsonClient` from `request`. (Though HTTP errors will still have to be "`setTimeout`ed" manually.)

### PR DESCRIPTION
**Pull request by elmigranto**
Closes #25. Version 1.2.2 is currently published in npm registry with `beta` tag.

### CODE REVIEW

**Review by j3k0 — APPROVED** [review]
All good. I had to dig a little to understand the "agent" option, apart from that it's crystal clear 👍

**Comment by elmigranto** [comment]
I wonder if you tried this updated version somewhere? There is a bug where it requests `/events/events` instead of `/events`. Fixing ASAP, but guess this hasn't been deployed anywhere yet? :)

**Comment by j3k0** [comment]
Indeed, I didn't run tests recently to check that events made it through. This isn't isn't in production yet. I suppose `ganomede-users` `ganomede-mailchimp` and `ganomede-reward` have to be updated now?

**Comment by j3k0** [comment]
```
ganomede-mailchimp-worker/package.json:    "ganomede-events": "^1.2.0",
ganomede-rewards/package.json:    "ganomede-events": "^1.2.2",
ganomede-users/package.json:    "ganomede-events": "^1.2.3",
```

**Pull request merged**
