### PR TITLE
#6 limit param

### PR DESCRIPTION
**Pull request by casualuser**

### CODE REVIEW

**Comment by j3k0** [comment]
@casualuser Please don't forget to make sure unit tests still pass (`npm test`), to update API.md documentation for the additional parameter and to add some unit tests that validates that the new parameter is working.

**Comment by casualuser** [comment]
@j3k0 please check updated pull request and provide feedback

**Comment by elmigranto** [comment]
@casualuser Can you make PR to merge into `develop` instead, please?

**Comment by elmigranto** [comment]
nvm, see #11

**Pull request closed without merging**
